export const data = [
    { color: '#DBDFF1',value:20 },
    { color: '#DBDFF1',value:22 },
    { color: '#DBDFF1',value:22 },
    { color: '#DBDFF1',value:25 },
    { color: '#DBDFF1',value:19 },
    { color: '#DBDFF1',value:33 },
    { color: '#DBDFF1',value:33 },
    { color: '#DBDFF1',value:33 },
    { color: '#DBDFF1',value:31 },
    { color: '#DBDFF1',value:31 },
    { color: '#DBDFF1',value:20 },
    { color: '#DBDFF1',value:17 },
    { color: '#DBDFF1',value:18 },
    { color: '#DBDFF1',value:31 },
    { color: '#DBDFF1',value:31 },
    { color: '#DBDFF1',value:10 },
    { color: '#DBDFF1',value:10 },
    { color: '#DBDFF1',value:5 },
    { color: '#FF708B',value:5 },
    {color: '#FF708B',value:5 },
    {color: '#FF708B',value:6 },
    {color: '#FF708B',value:6 },
    {color: '#FF708B',value:9 },
    {color: '#FF708B',value:11 },
    {color: '#FF708B',value:8 },
    {color: '#FF708B',value:13 },
    {color: '#FF708B',value:12 },
    { color: '#FF708B',value:4 },
    { color: '#FF708B',value:4 },

    { color: '#FF708B',value:8},

    { color: '#FF708B',value:5 },
    { color: '#DBDFF1',value:20 },
    { color: '#DBDFF1',value:22 },
    { color: '#DBDFF1',value:22 },
    { color: '#DBDFF1',value:25 },
    { color: '#DBDFF1',value:19 },
    { color: '#DBDFF1',value:33 },
    { color: '#DBDFF1',value:33 },
    { color: '#DBDFF1',value:33 },
    { color: '#DBDFF1',value:31 },
    { color: '#DBDFF1',value:31 },
    { color: '#DBDFF1',value:20 },
    { color: '#DBDFF1',value:17 },
    { color: '#DBDFF1',value:19 },
    { color: '#DBDFF1',value:30 },
    { color: '#DBDFF1',value:29 },
    { color: '#DBDFF1',value:10 },
    { color: '#DBDFF1',value:10 },
    { color: '#DBDFF1',value:5 },
    { color: '#DBDFF1',value:3 },
    { color: '#DBDFF1',value:3 },
    { color: '#DBDFF1',value:5 },
    { color: '#DBDFF1',value:19 },
    { color: '#DBDFF1',value:30 },
    { color: '#DBDFF1',value:29 },
    { color: '#DBDFF1',value:10 },
    { color: '#DBDFF1',value:10 },
    { color: '#DBDFF1',value:5 },
    { color: '#DBDFF1',value:5 },
    { color: '#DBDFF1',value:6 },
    { color: '#DBDFF1',value:5 },

    
    
  ];